### PR TITLE
add pre-requeriments install Node

### PR DESCRIPTION
**Pull request by EvertonMelo**
add pre-requeriments,

fonts:

https://launchpad.net/~smartcash/+archive/ubuntu/ppa

https://help.ubuntu.com/16.04/serverguide/index.html

### CODE REVIEW

**Comment by thesolarminer** [comment]
Dependencies are determined by PPA and will change as needed.

**Comment by EvertonMelo** [comment]
@thesolarminer 

Yes. 
The smartcash ( binary ) it is not compatible.
I see now.

would not it be nice to delete depreciated files? 

THe PPA has ubuntu files 14.04 LTS 0trusty1 Is this necessary?

**Comment by thesolarminer** [comment]
Yeah, Ubuntu 14 should be removed.  Updated readme/install.sh to add Ubuntu 18.

**Comment by EvertonMelo** [comment]
@thesolarminer 

I thought to insert **16.04 lts > above** but 

but the torque support is only for 18.04, it would be cohesive but there are other later versions.

Thanks.

**Pull request closed without merging**
